In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import data
import tests
%matplotlib inline

house_prices = data.HousePrices()

In [61]:
class MinMaxScaler:

    def __init__(self):
        self.min = None
        self.max = None

    def fit(self, X):
        """
        Compute and save the features min and max of shape (num_features,)
        (you can also save them with shape (1, num_features))
        :param X: array of shape (num_samples, num_features)
        :return: fitted scaler
        """
        # Workspace 1.1.a
        #BEGIN 
        # code here
        self.min = np.min(X, axis=0)
        self.max = np.max(X, axis=0)
        #END
        return self

    def transform(self, X):
        """
        Transform the given samples using the precomputed min and max
        :param X: np.array of shape (num_samples, num_features)
        :return: MinMax scaled X, of shape (num_samples, num_features)
        """
        # Workspace 1.1.b
        #BEGIN 
        # code here
        for feature in range(X.shape[1]):
            X[:, feature] = (X[:, feature] - self.min[feature]) / (self.max[feature] - self.min[feature])
        return X
        #END

    def fit_transform(self, X):
        """
        Fit using X and then transform it. Useful when we need to scale jsut once.
        """
        self.fit(X)
        return self.transform(X)

In [62]:
house_prices = data.HousePrices()
minmax_scaler = MinMaxScaler()
# MinMax works on 2-d arrays, so we just need to parse the prices as a single column/feature
# and then squeeze it back to 1-d array
house_prices.y_train = minmax_scaler.fit_transform(house_prices.y_train[:, None])[:, 0]
house_prices.y_test = minmax_scaler.transform(house_prices.y_test[:, None])[:, 0]

In [37]:
features = np.array([[1.55143777, 0.2644804, 0.0995576],
                         [0.22541014, 1.6967911, -0.45701382],
                         [0.12528546, -1.44263567, 0.7017054],
                         [-1.30567135, -0.86010032, -1.13522536]])
labels = np.array([136.70039877, 10.1003086, 44.67363091, -221.48398972])

X_hat = np.empty((features.shape[0], features.shape[1]))
X_hat = features - np.mean(features, axis=0)

# print(x_mean)
print(X_hat)
print(X_hat.T)
# print(alpha_matrix)

print(np.linalg.inv(np.transpose(X_hat).dot(X_hat) + 2))
print("\n\n")
# print(np.linalg.inv(np.transpose(X_hat).dot(X_hat) + alpha_matrix))
# print(np.transpose(X_hat).dot(labels))

# print(features[:, 0])
# print(features[:, 0] - 1)
# print(np.subtract(features[:, 0], 1))

[[ 1.40232227  0.34984652  0.29730165]
 [ 0.07629464  1.78215722 -0.25926978]
 [-0.02383004 -1.35726955  0.89944945]
 [-1.45478685 -0.7747342  -0.93748131]]
[[ 1.40232227  0.07629464 -0.02383004 -1.45478685]
 [ 0.34984652  1.78215722 -1.35726955 -0.7747342 ]
 [ 0.29730165 -0.25926978  0.89944945 -0.93748131]]
[[ 0.67220542 -0.24255507 -0.58161048]
 [-0.24255507  0.2226884   0.16951212]
 [-0.58161048  0.16951212  0.77545272]]





In [34]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print(np.linalg.inv(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [38]:
I = np.identity(features.shape[1])
print( 2 * I)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [11]:
from sklearn.linear_model import lasso_path
X = np.array([[1, 2, 3.1, 4.5], [2.3, 5.4, 4.3, 5.7], [1,2,3,4]]).T
y = np.array([1, 2, 3.1, 7])
_, coef_path, _ = lasso_path(X, y, alphas=[5.])
print(coef_path.shape)
print(coef_path)

(3, 1)
[[0.        ]
 [0.54231535]
 [0.        ]]


In [54]:
a=np.array([[16.154939900325]])
a[a > 25] = 25
a[a < -25] = -25
print(a)
ans=1 / (1 + np.exp(-a))
print(ans)

[[16.1549399]]
[[0.9999999]]


In [29]:
a=np.array([1,2])
a=a.reshape(2,1)
print(a.shape)
b=np.array([[0],[1]])
print(b.shape)

c=a-b
print(c.shape)
print(c)

(2, 1)
(2, 1)
(2, 1)
[[1]
 [1]]


In [55]:
y=np.array([0,1,1,1,0,2,3,2,3])
label_to_index=dict(zip(np.unique(y), range(len(np.unique(y)))))
index_to_label = {v: k for k, v in label_to_index.items()}

one_hot_encode = np.zeros((y.shape[0], len(label_to_index)), dtype=int)
for i in range(len(y)): # iterate over each sample
    for j in label_to_index.keys(): # iterate over each class_label
        if y[i] == j:
            one_hot_encode[i][label_to_index[j]] = 1

print(one_hot_encode)

[[1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 1]]


In [56]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
Y_onehot = onehot_encoder.fit_transform(y.reshape(-1,1))
print(Y_onehot)
print(Y_onehot[:,0])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 0. 0. 0. 1. 0. 0. 0. 0.]


In [57]:
one_hot_encode_2 = np.zeros((y.shape[0], len(label_to_index)), dtype=int)
for ind, val in enumerate(y):
    one_hot_encode_2[ind][val] = 1

print(one_hot_encode_2)

[[1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 1]]


In [63]:
class RidgeSelf(object):

    def __init__(self, alpha, normalize=False):
        """
        :param alpha: regularization parameter
        :param normalize: boolean whether to normalize the features or not
        """

        self.alpha = alpha  # our tuning / regularization parameter
        self.coefficients = None  # our weights vector, w (in formulae above)
        self.intercept = None  # our intercept parameter, b (in formulae above)
        self.normalize = normalize  # boolean whether to normalize the features or not
        self.scaler = StandardScaler()  # method by which to normalize the features (depends on self.normalize)

    def fit(self, X, y):
        """
        Fit the ridge model, train it using the provided data
        Calculate the number of non-zero coefficients in the model weights and the norm using np.linalg.norm
        :param X: training features (num_samples, num_features)
        :param y: target values (num_samples)
        :return: tuple (number of non-zeros coefficients of w, norm of w)
        """
        num_nonzero_coefs, coef_norm = 0, 0
        # Workspace 1.2.a
        # TO DO: compute w and b and store them in self.coef_ and self.intercept
        # HINT: use self.scaler first, if and only if self.normalize is True
        #BEGIN 
        # code here
        
        # normalize is required
        if self.normalize == True:
            self.scaler.fit(X)
            X = self.scaler.transform(X)
            # X = self.scaler.fit_transform(X)
        
        # compute X_hat
        X_hat = np.empty((X.shape[0], X.shape[1]))
        X_hat = X - np.mean(X, axis=0)
        I = np.identity(X.shape[1])
        
        # compute coef vector
        w_star = np.empty(X.shape[0])
        # print("x * x^T", (X_hat.dot(np.transpose(X_hat))).shape)
        # print("deno shape", (X_hat.dot(np.transpose(X_hat)) + alpha_matrix).shape)
        # print("1/deno shape", (1 / (X_hat.dot(np.transpose(X_hat)) + alpha_matrix) ).shape)
        # print("x^T * y", (np.transpose(X_hat).dot(y)).shape)
        w_star = (np.linalg.inv(np.transpose(X_hat).dot(X_hat) + self.alpha * I)).dot(np.transpose(X_hat)).dot(y)
        # w_star = np.dot(np.dot(np.linalg.inv(np.dot(X_hat.T, X_hat) + self.alpha * I), X_hat.T), y)
        self.coefficients = w_star

        # computer intercept
        sum = 0
        for sample in range(len(X)):
            sum += (y[sample] - (np.transpose(w_star).dot(X[sample])))
        self.intercept = sum/len(X)

        num_nonzero_coefs = np.count_nonzero(self.coefficients)
        coef_norm = np.linalg.norm(self.coefficients)
        #END
        return num_nonzero_coefs, coef_norm

    def evaluate(self, X, y):
        """
        Compute Root mean square error (RMSE) between the predicted values and the actual values of the test data
        :param X: instances array of shape (num_samples, num_features)
        :param y: the true targets, of shape (num_samples)
        :return: RMSE
        """

        # Workspace 1.2.b
        # TO DO: predict based on the test features and return the root mean squared error
        #BEGIN 
        # code here
        if self.normalize == True: # normalize the test data
            X = self.scaler.transform(X)
        y_hat = np.empty(y.shape)
        for sample in range(len(X)):
            y_hat[sample] = np.transpose(self.coefficients).dot(X[sample]) + self.intercept
        
        # y_hat = np.transpose(self.coefficients).dot(X) + self.intercept
        
        root_mean_squared_error = np.sqrt(np.mean((y_hat - y) ** 2))
        
        #END
        return root_mean_squared_error

In [64]:
ri = RidgeSelf(1e4, normalize=True)
ri.fit(house_prices.X_train, house_prices.y_train)

print(ri.coefficients)
print(ri.intercept)

print(ri.evaluate(house_prices.X_test, house_prices.y_test))

[-0.00065838  0.00442683  0.00892526 -0.00020149  0.00158773  0.00465773
  0.00528186  0.00176966  0.01096399  0.00757301  0.00443479 -0.00594338]
0.061247813321450045
0.028003667392365386


In [65]:
from sklearn.linear_model import Ridge

scaler = StandardScaler()
alphas = [0.01, 0.05, 0.1, 0.2, 0.3, 1.0, 10.0, 100.0, 300.0, 500.0, 1e3, 1.5e3, 2e3, 5e3, 1e4]
rmses = []

for alpha in alphas:

    X = scaler.fit_transform(house_prices.X_train)
    X = house_prices.X_train
    y = house_prices.y_train

    r = Ridge(alpha=alpha)
    r.fit(X, y)

    X_test = scaler.transform(house_prices.X_test)
    X_test = house_prices.X_test

    # print(r.coef_)
    # print(r.intercept_)

    y_hat = r.predict(X_test)
    rmse = np.sqrt(np.mean((y_hat - house_prices.y_test) ** 2))
    rmses.append(rmse)

print(rmses)


[0.026894935550812665, 0.026895024833162473, 0.026895136532495877, 0.026895360250842715, 0.026895584392564027, 0.026897164954318042, 0.026918870561759442, 0.027124816295421943, 0.027333759286632564, 0.027414780350526323, 0.02749422357803399, 0.027536368618381258, 0.027575056257770066, 0.02786459099894152, 0.028388629911411965]


In [66]:
a=np.array([0.026894911608571895, 0.026894905078820863, 0.02689489691715849, 0.026894880595324112, 0.026894864275439887, 0.026894750092151743, 0.026893290679514736, 0.026879560001868665, 0.026854299069622667, 0.02683553442791724, 0.026812139357760303, 0.02681517129952617, 0.026837971053934276, 0.027190858357845734, 0.028003667392365386])
print(a)

[0.02689491 0.02689491 0.0268949  0.02689488 0.02689486 0.02689475
 0.02689329 0.02687956 0.0268543  0.02683553 0.02681214 0.02681517
 0.02683797 0.02719086 0.02800367]


In [22]:
from sklearn.linear_model import lasso_path


class LassoSelf(object):
    def __init__(self, alpha, normalize=False):
        """
        :param alpha: regularization parameter
        :param normalize: boolean whether to normalize the features or not
        """
        self.alpha = alpha  # our tuning / regularization parameter
        self.coefficients = None  # our weights vector, w (in formulae above)
        self.intercept = None  # our intercept parameter, b (in formulae above)
        self.normalize = normalize  # boolean whether to normalize the features or not
        self.scaler = StandardScaler()  # method by which to normalize the features (depends on self.normalize)

    def fit(self, X, y):
        """
        Fit the lasso model, train it using the provided data
        Calculate the number of non-zero coefficients in the model weights and the norm using np.linalg.norm
        :param X: training features (num_samples, num_features)
        :param y: target values (num_samples)
        :return: tuple (number of non-zeros coefficients of w: scalar, norm of w: scalar)
        """

        num_nonzero_coefs, coef_norm = 0, 0
        # Workspace 1.4.a
        # TO DO: compute w and b and store then in self.coef_ and self.intercept
        # TO DO: call lasso_path on the centered features to compute self.coef_
        # HINT: use self.scaler first, if and only if self.normalize is True
        #BEGIN 
        # code here
        # normalize is required
        if self.normalize == True:
            self.scaler.fit(X)
            X = self.scaler.transform(X)
                
        # compute X_hat
        X_hat = np.empty((X.shape[0], X.shape[1]))
        X_hat = X - np.mean(X, axis=0)

        _, w_star, _ = lasso_path(X_hat, y, alphas=[self.alpha])

        self.coefficients = w_star.T

        # computer intercept
        sum = 0
        for sample in range(len(X)):
            sum += (y[sample] - (np.transpose(w_star).dot(X[sample])))
        self.intercept = sum/len(X)

        num_nonzero_coefs = np.count_nonzero(self.coefficients)
        coef_norm = np.linalg.norm(self.coefficients)
        #END
        return num_nonzero_coefs, coef_norm

    def evaluate(self, X, y):
        """
        Compute Root mean square error (RMSE) between the predicted values and the actual values  of the test data
        :param X: features array, shape (num_samples, num_features)
        :param y: true targets, shape (num_samples)
        :return: RMSE
        """
        root_mean_squared_error = 0
        # Workspace 1.4.b
        # TO DO: predict based on the test features and return the mean_squared_error
        #BEGIN 
        # code here
        if self.normalize == True: # normalize the test data
            X = self.scaler.transform(X)
        y_hat = np.empty(y.shape)
        for sample in range(len(X)):
            # y_hat[sample] = np.transpose(self.coefficients).dot(X[sample]) + self.intercept
            y_hat[sample] = self.coefficients.dot(X[sample]) + self.intercept
                
        root_mean_squared_error = np.sqrt(np.mean((y_hat - y) ** 2))
        #END
        return root_mean_squared_error

In [29]:
ri = LassoSelf(0.2, normalize=False)
ri.fit(house_prices.X_train, house_prices.y_train)

print(ri.coefficients)
print(ri.intercept)

[[-0.00000000e+00  0.00000000e+00  3.77327633e-05 -3.55267717e-08
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  4.49571972e-07 -4.43693966e-05]]
[0.07052146]


In [30]:
from sklearn.linear_model import Lasso

scaler = StandardScaler()

# X = scaler.fit_transform(house_prices.X_train)
X = house_prices.X_train
y = house_prices.y_train

l = Lasso(alpha=0.2)
l.fit(X, y)

# X_test = scaler.transform(house_prices.X_test)

print(l.coef_)
print(l.intercept_)

[-0.00000000e+00  0.00000000e+00  3.77327633e-05 -3.55267717e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  4.49571972e-07 -4.43693966e-05]
0.07052146115486504


In [31]:
from sklearn.metrics import recall_score

class LogisticRegressionSelf:

    def __init__(self, eta=0.1, alpha=0):
        """
        Create a logistic regression classifier
        :param eta: Learning rate
        :param alpha: We will use this parameter later (IN BONUS)
        """

        self.w = None  # uninitialized w
        self.eta = eta  # learning rate
        self.initialized = False # flag used to initialize w only once, it allows calling fit multiple times
        self.alpha = alpha  # regularization / penalty term (USED IN BONUS)

    def sigmoid(self, x, threshold=25.0):
        """

        :param x: features array of shape (num_samples, num_features + 1) (zero-th column appended)
        :param threshold: the truncating threshold for np.exp, default to 25.0
        :return: sigmoid values , of shape (num_samples,)
        """
        # Workspace 2.1
        # TO DO: Complete this function to return the output of applying the sigmoid function to the score
        #BEGIN 
        # code here
        # print("x shape is: ", x.shape)
        # print("w shape is: ", self.w.shape)
        sigmoid_val = np.empty((len(x),))
        # for i in range(len(x)):
        #     sigmoid_val[i] = np.dot(np.transpose(self.w), x[i])
        sigmoid_val = np.dot(x, self.w)
        # print("sigmoid_val is: ", sigmoid_val)
        sigmoid_val[sigmoid_val > threshold] = threshold
        sigmoid_val[sigmoid_val < -threshold] = -threshold

        # for i in range(len(sigmoid_val)):
        #     sigmoid_val[i] = 1 / (1 + np.exp(-sigmoid_val[i]))
        
        return 1 / (1 + np.exp(-sigmoid_val))
        #END

    def compute_gradient(self, x, y):
        """
        Return the derivative of the cost w.r.t to the weights. Don't forget to average by batch_size
        :param x:  Feature vector, shape (batch_size, num_features +1), with zero-th column appended
        :param y: real binary class label, shape (batch_size)
        :return: gradient of shape (num_features + 1,)
        """

        # Workspace 2.2
        # TO DO: Finish this function to compute the gradient
        gradient = np.zeros((x.shape[1], ))
        #BEGIN 
        # code here
        sigmoid_val = self.sigmoid(x)
        # print("sigmoid_val-y shape is: ", (sigmoid_val - y).shape)
        gradient = (1/len(x)) * np.transpose(x).dot(sigmoid_val - y.reshape(len(x), 1))
        # print("gradient shape is: ", gradient.shape)
        #END
        return gradient

    def batch_update(self, batch_x, batch_y):
        """
        Single self.w update using the batch.
        :param batch_x: array of features (includes the constant feature at column 0), of shape (batch_size, num_features + 1)
        :param batch_y: array of target values, shape (batch_size,)
        :return: nothing
        """

        # Workspace 2.3
        #BEGIN 
        # code here
        # print("weight shape is: ", self.w.shape)
        self.w -= self.eta * self.compute_gradient(batch_x, batch_y)
        #END

    def fit(self, X, y, epochs=1, batch_size=1, validation_X=None, validation_y=None):
        """
        train the LogisticRegression
        :param X: training features, shape (num_samples, num_features)
        :param y: training labels, shape (num_samples,)
        :param epochs: number of epochs, integer
        :param batch_size: size of batch for gradient update, 1 for SGD
        :param validation_X: validation rows, should default to training data if not provided
        :param validation_y: validation labels
        :return: recall score at the end of each epoch on validation data
        """

        if validation_X is None:
            validation_X, validation_y = X, y
        metrics = []
        # Workspace  2.4
        # TO DO: Process X to append the zero-th constant column and call self.optimize
        # TO DO: Compute average recall on the validation data at the end of each epoch
        # HINT: make sure to initialize w
        #BEGIN 
        # code here
        X = np.concatenate([np.ones((X.shape[0], 1)), X], axis=1)  # We append zero-th column
        self.w = np.full((X.shape[1], 1), (1/len(X))) # initialize w
        for _ in range(1, epochs+1):
            self.optimize(X, y, batch_size)
            y_hat = self.predict(validation_X)
            metrics.append(recall_score(validation_y, y_hat))
        #END
        return np.array(metrics)

    def predict(self, X):
        """
        :param X: features array, shape (num_samples, num_features) (without the constant column)
        :return: predicted binary label, shape (num_samples,)
        """
        # Workspace 2.5
        y_hat = np.zeros((X.shape[0],))
        X = np.concatenate([np.ones((X.shape[0], 1)), X], axis=1)  # We append zero-th column
        #BEGIN 
        # code here
        y_hat = self.sigmoid(X)
        y_hat[y_hat >= 0.5] = 1
        y_hat[y_hat < 0.5] = 0
        #END
        return y_hat

    def optimize(self, X, y, batch_size):
        """
        Perform one epoch batch gradient on shuffled data
        :param X: np.array of shape (num_samples, num_features +1), The training data with zero-th column appended
        :param y: target values of shape (num_samples,)
        :param batch_size: batch_size of the batch_update
        :return: None
        """
        indices = np.random.permutation(len(X))
        for i in range(0, X.shape[0], batch_size):
            batch_x = X[indices[i:i + batch_size]]
            batch_y = y[indices[i:i + batch_size]]
            self.batch_update(batch_x, batch_y)

In [60]:
y_hat = np.zeros((X.shape[0],))
print(y_hat.astype(int))

[0 0 0 ... 0 0 0]


In [75]:
w = np.full((6, ), (1/5))
print(w)
# q = np.full((5, ), (1/2))
# print(w+q)
# print(w)
# print(w[1:])
print(w+ 0* w)

[0.2 0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2 0.2]
