In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tests
import data

In [2]:
multi_blobs = data.DataBlobs(centers=6, std=1.3)
X_train = multi_blobs.X_train
X_train.shape

(280, 2)

In [3]:
random_ids = np.random.permutation(X_train.shape[0])
# random_ids
centroids = X_train[random_ids[:6]]
centroids

array([[ 4.58873227,  4.69930375],
       [-6.88190121, -2.83660739],
       [-4.64556821, -3.05161524],
       [-3.0890414 ,  0.9456588 ],
       [-3.94088339, -1.45953048],
       [-3.36611414,  0.74310899]])

In [4]:
(X_train - centroids[0,:])[:5]

array([[ -8.02477477,  -6.47616765],
       [ -6.08617824,   3.2596494 ],
       [ -1.58794355, -11.2478215 ],
       [ -6.69540964,  -7.91209446],
       [ -4.48092854,   2.39873457]])

In [16]:
(X_train - centroids[0])[:5]

array([[ -8.70751397,  -6.59190192],
       [ -6.76891744,   3.14391514],
       [ -2.27068275, -11.36355576],
       [ -7.37814884,  -8.02782873],
       [ -5.16366774,   2.28300031]])

In [5]:
distances_matrix = np.zeros((X_train.shape[0], 6))
for k in range(6):
    distances_matrix[:,k] = np.linalg.norm(X_train - centroids[k, :], axis=1)
distances_matrix.shape

(280, 6)

In [6]:
print(distances_matrix[174])
# np.argmin(distances_matrix[174])
np.argmin(distances_matrix, axis=1).shape

[ 4.76676715 14.18143447 13.14343367  8.90767015 11.40961009  9.22786506]


(280,)

In [9]:
a = np.array([1,2,2,2,3,4])
len(np.unique(a))
np.unique(a).shape

(4,)

In [5]:
a = np.array([1,2,3,4])
print(np.square(a))
print(a/np.sum(a))
np.sum(a/np.sum(a))

[ 1  4  9 16]
[0.1 0.2 0.3 0.4]


1.0

In [6]:
np.linalg.norm(1-5, ord=2)

ValueError: Improper number of dimensions to norm.

In [10]:
np.round(-1e-6)

-0.0

In [11]:
a = np.array([[26, -26], [50, -50]])
a[a<-25]=-25
a[a>25]=25
print(a)

[[ 25 -25]
 [ 25 -25]]


In [15]:
np.random.randn(3, 4)/(12**0.5)

array([[-0.29731271, -0.24262083,  0.3069672 ,  0.33624573],
       [ 0.05074562, -0.11975806,  0.19542231,  0.19057906],
       [ 0.48031506,  0.38114062,  0.03304932, -0.24991183]])

In [17]:
np.random.randn(1, 4).shape

(1, 4)

In [11]:
a=np.array([1,2,3,4])
a > 2
b=np.array([1,2,3,5])
b[a>2]

array([3, 5])

In [7]:
np.exp(2)

7.38905609893065

In [12]:
np.sum(a==b)

3

In [13]:
a=np.array([1,2,3,4])
print(1-np.square(a))

[  0  -3  -8 -15]


In [5]:
x = [0 for _ in range(4)]*4

In [6]:
x

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [7]:
x[0][0] = 1

TypeError: 'int' object does not support item assignment

In [4]:
x

[[1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]]