In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tests
import data

In [2]:
multi_blobs = data.DataBlobs(centers=6, std=1.3)
X_train = multi_blobs.X_train
X_train.shape

(280, 2)

In [5]:
random_ids = np.random.permutation(X_train.shape[0])
# random_ids
centroids = X_train[random_ids[:6]]
centroids

array([[ 5.27147146,  4.81503802],
       [-4.1295825 , -1.41974473],
       [ 1.22273916,  9.04199806],
       [-4.58186943, 10.17910891],
       [-1.47840337,  8.31414016],
       [-5.55005333, -1.75335845]])

In [8]:
(X_train - centroids[0,:])[:5]

array([[ -8.70751397,  -6.59190192],
       [ -6.76891744,   3.14391514],
       [ -2.27068275, -11.36355576],
       [ -7.37814884,  -8.02782873],
       [ -5.16366774,   2.28300031]])

In [16]:
(X_train - centroids[0])[:5]

array([[ -8.70751397,  -6.59190192],
       [ -6.76891744,   3.14391514],
       [ -2.27068275, -11.36355576],
       [ -7.37814884,  -8.02782873],
       [ -5.16366774,   2.28300031]])

In [9]:
distances_matrix = np.zeros((X_train.shape[0], 6))
for k in range(6):
    distances_matrix[:,k] = np.linalg.norm(X_train - centroids[k, :], axis=1)
distances_matrix.shape

(280, 6)

In [15]:
print(distances_matrix[174])
# np.argmin(distances_matrix[174])
np.argmin(distances_matrix, axis=1).shape

[ 5.1289879  11.46933567  0.72773417  6.48584711  3.15767344 12.52063067]


(280,)